### ISSUE TITLE
made server crash several times in a few minutes

### ISSUE THREAD

**Issue by anaxios** [NucleoidMC/leukocyte#15]
I'm not sure what info is helpful. sorry. here's one of the several reports.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 7/2/21, 2:50 AM
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1628 cannot be cast to class net.minecraft.class_3222 (net.minecraft.class_1628 and net.minecraft.class_3222 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @1ed6388a)
	at net.minecraft.class_2344.handler$zkm000$breakFarmland(class_2344.java:525)
	at net.minecraft.class_2344.method_9554(class_2344.java:97)
	at net.minecraft.class_1297.method_5623(class_1297.java:1153)
	at net.minecraft.class_1309.method_5623(class_1309.java:318)
	at net.minecraft.class_1297.method_5784(class_1297.java:640)
	at net.minecraft.class_1309.method_26318(class_1309.java:2240)
	at net.minecraft.class_1309.method_6091(class_1309.java:2185)
	at net.minecraft.class_1309.method_6007(class_1309.java:2636)
	at net.minecraft.class_1308.method_6007(class_1308.java:538)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1309.method_5773(class_1309.java:2342)
	at net.minecraft.class_1308.method_5773(class_1308.java:338)
	at net.minecraft.class_1628.method_5773(class_1628.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:656)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:418)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:393)
	at net.minecraft.server.MinecraftServer.redirect$zpk000$ficUpdateSuppressionCrashTick(MinecraftServer.java:4275)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
	at net.minecraft.class_3176.method_3813(class_3176.java:334)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
	at net.minecraft.server.MinecraftServer.handler$bbf000$modifiedRunLoop(MinecraftServer.java:5893)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2344.handler$zkm000$breakFarmland(class_2344.java:525)
	at net.minecraft.class_2344.method_9554(class_2344.java:97)
	at net.minecraft.class_1297.method_5623(class_1297.java:1153)
	at net.minecraft.class_1309.method_5623(class_1309.java:318)
	at net.minecraft.class_1297.method_5784(class_1297.java:640)
	at net.minecraft.class_1309.method_26318(class_1309.java:2240)
	at net.minecraft.class_1309.method_6091(class_1309.java:2185)
	at net.minecraft.class_1309.method_6007(class_1309.java:2636)
	at net.minecraft.class_1308.method_6007(class_1308.java:538)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1309.method_5773(class_1309.java:2342)
	at net.minecraft.class_1308.method_5773(class_1308.java:338)
	at net.minecraft.class_1628.method_5773(class_1628.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:656)

-- Entity being ticked --
Details:
	Entity Type: minecraft:spider (net.minecraft.class_1628)
	Entity ID: 124
	Entity Name: Spider
	Entity's Exact location: 482.95, 64.00, -1401.87
	Entity's Block location: World: (482,64,-1402), Section: (at 2,0,6 in 30,4,-88; chunk contains blocks 480,0,-1408 to 495,255,-1393), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Entity's Momentum: -0.07, -0.52, 0.01
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:418)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:393)
	at net.minecraft.server.MinecraftServer.redirect$zpk000$ficUpdateSuppressionCrashTick(MinecraftServer.java:4275)

-- Affected level --
Details:
	All players: 3 total; [class_3222['SOPHRONIOS'/119, l='ServerLevel[Chanklas]', x=443.83, y=64.00, z=-1387.33], class_3222['I_Am_Snowbug'/120, l='ServerLevel[Chanklas]', x=12323.09, y=56.96, z=759.43], class_3222['LeoMCRN'/127, l='ServerLevel[Chanklas]', x=589.35, y=43.00, z=-835.92]]
	Chunk stats: 5990
	Level dimension: minecraft:overworld
	Level spawn location: World: (77,68,-42), Section: (at 13,4,6 in 4,4,-3; chunk contains blocks 64,0,-48 to 79,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 52964331 game time, 61921440 day time
	Level name: Chanklas
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 64357 (now: false), thunder time: 76115 (now: false)
	Known server brands: Paper, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
	at net.minecraft.class_3176.method_3813(class_3176.java:334)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
	at net.minecraft.server.MinecraftServer.handler$bbf000$modifiedRunLoop(MinecraftServer.java:5893)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Linux (amd64) version 5.4.0-65-generic
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1393568744 bytes (1329 MiB) / 3984588800 bytes (3800 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2643 v3 @ 3.40GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 3.40
	Number of physical packages: 2
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: ASPEED Graphics Family
	Graphics card #0 vendor: ASPEED Technology, Inc. (0x1a03)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x2000
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 186264.13
	Virtual memory used (MB): 243993.53
	Swap memory total (MB): 57343.99
	Swap memory used (MB): 8856.80
	JVM Flags: 2 total; -Xmx4096M -Xms512M
	Fabric Mods: 
		adorn: Adorn 2.0.0+1.17
		carpet: Carpet Mod 1.4.40
		carpet-autocraftingtable: Carpet-AutoCraftingTable 1.4.35
		carpet-extra: Carpet Extra 1.4.40
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		chunky: Chunky 1.2.86
		com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b4463d5
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121d5
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		inmis: Inmis 2.3.1-1.17
		invview: InvView 1.4.3-1.17+
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 16
		ledger: Ledger 1.0.1
		leukocyte: Leukocyte 0.3.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.2
		lootstrap: Lootstrap 1.1.0
		minecraft: Minecraft 1.17
		omega-config: OmegaConfig 1.0.4
		org_apache_commons_commons-compress: commons-compress 1.19
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_tukaani_xz: xz 1.8
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc1-1.17
		stimuli: Stimuli 0.2.0+1.17
		textile_backup: Textile Backup 2.1.0-1.17
		voicechat: Simple Voice Chat 1.17-1.2.3
		waystones: Waystones 2.0.1
		worldedit: WorldEdit 7.2.6-SNAPSHOT+5844-728a152
	Loaded Scarpet Apps: 
		silk_budding_amethyst
		silk_spawners
		shulkerboxes
		veinminer
	Player Count: 4 / 10; [class_3222['SOPHRONIOS'/119, l='ServerLevel[Chanklas]', x=443.83, y=64.00, z=-1387.33], class_3222['I_Am_Snowbug'/120, l='ServerLevel[Chanklas]', x=12323.09, y=56.96, z=759.43], class_3222['LeoMCRN'/127, l='ServerLevel[Chanklas]', x=589.35, y=43.00, z=-835.92], class_3222['JoDucc'/566, l='ServerLevel[Chanklas]', x=79.92, y=47.00, z=416.05]]
	Data Packs: vanilla (incompatible), file/bukkit (incompatible), Fabric Mods, file/anti creeper grief v1.1.0.zip, file/anti enderman grief v1.1.0.zip, file/anti ghast grief v1.1.0.zip, file/confetti creepers v2.2.0.zip, file/custom villager shops v1.2.0.zip, file/double shulker shells v1.3.0.zip, file/dragon drops v1.3.0.zip, file/VanillaTweaks_c728488.zip, file/armor statues v2.8.1.zip, file/more mob heads v2.9.1.zip, file/player head drops v1.1.0.zip, file/silence mobs v1.1.0.zip, file/tag v2.1.0.zip, file/villager death messages v1.2.1.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by haykam821** [comment]
This issue was fixed in Stimuli 0.2.1, which is not currently bundled with Leukocyte (Stimuli 0.2.0 is bundled instead). You can fix this issue by [downloading a newer version of Stimuli](https://maven.nucleoid.xyz/xyz/nucleoid/stimuli/0.2.2%2B1.17/stimuli-0.2.2%2B1.17.jar) which will replace the bundled version.

**Comment by anaxios** [comment]
great! thank you. Just add to mods folder like normal?

**Comment by haykam821** [comment]
Yep. I think this issue should be left open though so that Leukocyte can update its bundled Stimuli to 0.2.2.

**Comment by anaxios** [comment]
ok
